# admintoolbox
$path = "$workingdirectory/modules/AdminToolbox/ChangeLog.md"; $step = Get-Content $path | Select-Object -Last 1; $step2 = $step.trimstart('* **'); $step3 = ($step2).split('*'); [version]$step4 = ($step3 | Select-Object -First 1); [string]$major = $step4.major; [string]$minor = $step4.minor; [string]$build = ($step4.build); [string]$revision = ($step4.revision + 1); "`n* **" + $major + '.' + $minor + '.' + $build + '.' + $revision + '** CI Maintenance Release' | Out-File $path -Append -NoNewline
#activedirectory
$path = "$workingdirectory/modules/AdminToolbox.ActiveDirectory/ChangeLog.md"; $step = Get-Content $path | Select-Object -Last 1; $step2 = $step.trimstart('* **'); $step3 = ($step2).split('*'); [version]$step4 = ($step3 | Select-Object -First 1); [string]$major = $step4.major; [string]$minor = $step4.minor; [string]$build = ($step4.build); [string]$revision = ($step4.revision + 1); "`n* **" + $major + '.' + $minor + '.' + $build + '.' + $revision + '** CI Maintenance Release' | Out-File $path -Append -NoNewline
#endpointmanagement
$path = "$workingdirectory/modules/AdminToolbox.EndpointManagement/ChangeLog.md" ; $step = Get-Content $path | Select-Object -Last 1; $step2 = $step.trimstart('* **'); $step3 = ($step2).split('*'); [version]$step4 = ($step3 | Select-Object -First 1); [string]$major = $step4.major; [string]$minor = $step4.minor; [string]$build = ($step4.build); [string]$revision = ($step4.revision + 1); "`n* **" + $major + '.' + $minor + '.' + $build + '.' + $revision + '** CI Maintenance Release' | Out-File $path -Append -NoNewline
#Exchange
$path = "$workingdirectory/modules/AdminToolbox.Exchange/ChangeLog.md"; $step = Get-Content $path | Select-Object -Last 1; $step2 = $step.trimstart('* **'); $step3 = ($step2).split('*'); [version]$step4 = ($step3 | Select-Object -First 1); [string]$major = $step4.major; [string]$minor = $step4.minor; [string]$build = ($step4.build); [string]$revision = ($step4.revision + 1); "`n* **" + $major + '.' + $minor + '.' + $build + '.' + $revision + '** CI Maintenance Release' | Out-File $path -Append -NoNewline
#fftools
$path = "$workingdirectory/modules/AdminToolbox.FFTools/ChangeLog.md"; $step = Get-Content $path | Select-Object -Last 1; $step2 = $step.trimstart('* **'); $step3 = ($step2).split('*'); [version]$step4 = ($step3 | Select-Object -First 1); [string]$major = $step4.major; [string]$minor = $step4.minor; [string]$build = ($step4.build); [string]$revision = ($step4.revision + 1); "`n* **" + $major + '.' + $minor + '.' + $build + '.' + $revision + '** CI Maintenance Release' | Out-File $path -Append -NoNewline
#filemanagement
$path = "$workingdirectory/modules/AdminToolbox.FileManagement/ChangeLog.md"; $step = Get-Content $path | Select-Object -Last 1; $step2 = $step.trimstart('* **'); $step3 = ($step2).split('*'); [version]$step4 = ($step3 | Select-Object -First 1); [string]$major = $step4.major; [string]$minor = $step4.minor; [string]$build = ($step4.build); [string]$revision = ($step4.revision + 1); "`n* **" + $major + '.' + $minor + '.' + $build + '.' + $revision + '** CI Maintenance Release' | Out-File $path -Append -NoNewline
#fun
$path = "$workingdirectory/modules/AdminToolbox.Fun/ChangeLog.md"; $step = Get-Content $path | Select-Object -Last 1; $step2 = $step.trimstart('* **'); $step3 = ($step2).split('*'); [version]$step4 = ($step3 | Select-Object -First 1); [string]$major = $step4.major; [string]$minor = $step4.minor; [string]$build = ($step4.build); [string]$revision = ($step4.revision + 1); "`n* **" + $major + '.' + $minor + '.' + $build + '.' + $revision + '** CI Maintenance Release' | Out-File $path -Append -NoNewline
#msgraph
$path = "$workingdirectory/modules/AdminToolbox.MSGraph/ChangeLog.md"; $step = Get-Content $path | Select-Object -Last 1; $step2 = $step.trimstart('* **'); $step3 = ($step2).split('*'); [version]$step4 = ($step3 | Select-Object -First 1); [string]$major = $step4.major; [string]$minor = $step4.minor; [string]$build = ($step4.build); [string]$revision = ($step4.revision + 1); "`n* **" + $major + '.' + $minor + '.' + $build + '.' + $revision + '** CI Maintenance Release' | Out-File $path -Append -NoNewline
#networking
$path = "$workingdirectory/modules/AdminToolbox.Networking/ChangeLog.md"; $step = Get-Content $path | Select-Object -Last 1; $step2 = $step.trimstart('* **'); $step3 = ($step2).split('*'); [version]$step4 = ($step3 | Select-Object -First 1); [string]$major = $step4.major; [string]$minor = $step4.minor; [string]$build = ($step4.build); [string]$revision = ($step4.revision + 1); "`n* **" + $major + '.' + $minor + '.' + $build + '.' + $revision + '** CI Maintenance Release' | Out-File $path -Append -NoNewline
#office365
$path = "$workingdirectory/modules/AdminToolbox.Office365/ChangeLog.md"; $step = Get-Content $path | Select-Object -Last 1; $step2 = $step.trimstart('* **'); $step3 = ($step2).split('*'); [version]$step4 = ($step3 | Select-Object -First 1); [string]$major = $step4.major; [string]$minor = $step4.minor; [string]$build = ($step4.build); [string]$revision = ($step4.revision + 1); "`n* **" + $major + '.' + $minor + '.' + $build + '.' + $revision + '** CI Maintenance Release' | Out-File $path -Append -NoNewline
#remoting
$path = "$workingdirectory/modules/AdminToolbox.Remoting/ChangeLog.md"; $step = Get-Content $path | Select-Object -Last 1; $step2 = $step.trimstart('* **'); $step3 = ($step2).split('*'); [version]$step4 = ($step3 | Select-Object -First 1); [string]$major = $step4.major; [string]$minor = $step4.minor; [string]$build = ($step4.build); [string]$revision = ($step4.revision + 1); "`n* **" + $major + '.' + $minor + '.' + $build + '.' + $revision + '** CI Maintenance Release' | Out-File $path -Append -NoNewline
#vmwareautomate
$path = "$workingdirectory/modules/AdminToolbox.VMWareAutomate/ChangeLog.md"; $step = Get-Content $path | Select-Object -Last 1; $step2 = $step.trimstart('* **'); $step3 = ($step2).split('*'); [version]$step4 = ($step3 | Select-Object -First 1); [string]$major = $step4.major; [string]$minor = $step4.minor; [string]$build = ($step4.build); [string]$revision = ($step4.revision + 1); "`n* **" + $major + '.' + $minor + '.' + $build + '.' + $revision + '** CI Maintenance Release' | Out-File $path -Append -NoNewline
#fortiwizard
$path = "$workingdirectory/modules/Admintoolbox.FortiWizard/ChangeLog.md"; $step = Get-Content $path | Select-Object -Last 1; $step2 = $step.trimstart('* **'); $step3 = ($step2).split('*'); [version]$step4 = ($step3 | Select-Object -First 1); [string]$major = $step4.major; [string]$minor = $step4.minor; [string]$build = ($step4.build); [string]$revision = ($step4.revision + 1); "`n* **" + $major + '.' + $minor + '.' + $build + '.' + $revision + '** CI Maintenance Release' | Out-File $path -Append -NoNewline